services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      # A senha virá de um ficheiro .env para mais segurança
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Monta o nosso script de inicialização para criar os bancos
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      mysql-db:
        condition: service_healthy # Aguarda o MySQL ficar saudável

  produto-service:
    build:
      context: ./produto-service
    container_name: produto-service
    ports:
      - "8100:8100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/produtos_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_started

  pedido-service:
    build:
      context: ./pedido-service
    container_name: pedido-service
    ports:
      - "8200:8200"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/pedidos_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      # Configuração da segurança simples
      SPRING_SECURITY_USER_NAME: mateus
      SPRING_SECURITY_USER_PASSWORD: senha123
    depends_on:
      produto-service:
        condition: service_started

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8700:8700"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      pedido-service:
        condition: service_started

volumes:
  mysql_data:
