
services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mateusdb 
      MYSQL_DATABASE: produtos_db,pedidos_db 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      mysql-db:
        condition: service_healthy 
    healthcheck: 
      test: "curl -f http://localhost:8761/ || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10


  produto-service:
    build:
      context: ./produto-service
    container_name: produto-service
    ports:
      - "8100:8100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/produtos_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy 

  # Servico de Pedidos
  pedido-service:
    build:
      context: ./pedido-service
    container_name: pedido-service
    ports:
      - "8200:8200"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/pedidos_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      produto-service:
        condition: service_started # Inicia depois do produto-service

  # Servico do API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8700:8700"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      pedido-service:
        condition: service_started 

# Define um volume nomeado para persistir os dados do MySQL
volumes:
  mysql_data:
